services:
  db:
    container_name: ow_db
    image: postgres:16-alpine@sha256:84fb5d5bdd7d47f1889f325e534f3ce643f853f460832c8a61949f5391b8dc42
    restart: always
    environment:
      POSTGRES_PASSWORD: owpassword123
      POSTGRES_USER: ow
      POSTGRES_DB: ow
    ports:
      - "4010:5432"
  jaeger:
    container_name: ow_jaeger
    image: jaegertracing/all-in-one:latest@sha256:c87fc1d9b22766284168abb2ac57ac2160dfc26484e4f965ff2dcc6b849b263a
    ports:
      - '4317:4317'
      - '4318:4318'
      - '16686:16686'
